version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: caririfest-postgres
    environment:
      POSTGRES_DB: caririfest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  api:
    image: caririfest-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/caririfest
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin