spring:
  application:
    name: caririfest-api

  datasource:
    url: jdbc:postgresql://yamanote.proxy.rlwy.net:12838/railway
    username: postgres
    password: VnctMWKlUcrwBtsRYMHHCqkmZERzQvzQ
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  mail:
    host: smtp.seuprovedor.com
    port: 587
    username: seu_email@dominio.com
    password: sua_senha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
    port: ${PORT:8080}
    address: 0.0.0.0

stripe:
    secret: sk_test_51SUVUOQgaqHCARe3XnIQzvveTe11MsO4zOTQr2gPvAwK69AgcEDiq86lELfjGM6sgEqMCvdeYZLTn9s4hMY8kTkv003vCJ4vEk